In [1]:
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [2]:
datadir='/home/dell/Documents/python_tools/array_from_images/Dataset/'
categories=['Cat','Dog']

In [26]:
for category in categories:
    path=os.path.join(datadir,category)
    for img in os.listdir(path):
        img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
        #break
        print(img_array,'            ',img_array.shape)
    #break

[[ 48  48  53 ...  76  68  47]
 [ 52  51  57 ...  77  69  49]
 [ 55  55  60 ...  71  61  43]
 ...
 [130 129 128 ...  63  58  56]
 [131 131 131 ...  58  50  46]
 [128 134 135 ...  61  53  54]]              (345, 500)
[[ 95  97 100 ...  28  27  26]
 [ 91  92  96 ...  28  27  26]
 [ 86  87  90 ...  28  27  26]
 ...
 [ 75  74  78 ...   3   3   3]
 [ 74  73  76 ...   3   3   3]
 [ 71  72  77 ...   3   3   3]]              (374, 500)
[[255 249 251 ... 255 255 255]
 [251 255 254 ... 255 255 255]
 [248 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]              (256, 334)
[[62 61 61 ... 52 55 50]
 [61 61 61 ... 51 55 51]
 [61 61 61 ... 49 54 52]
 ...
 [34 34 33 ... 40 40 38]
 [26 26 25 ... 40 40 38]
 [17 17 16 ... 40 40 38]]              (500, 345)
[[116 112 112 ...  24  22  21]
 [115 111 111 ...  22  20  20]
 [114 111 111 ...  23  22  23]
 ...
 [106  95  88 ...  73  72  73]
 [113 100  90 ...  74  75  77]
 [113  99  8

In [20]:
img_array

array([[  1,   1,   1, ...,  14,  12,   1],
       [  1,   1,   1, ...,  12,   8,   9],
       [  1,   1,   1, ...,   9,   5,   8],
       ...,
       [ 99,  99,  98, ..., 135, 136, 134],
       [ 99,  98,  98, ..., 136, 137, 135],
       [ 98,  98,  99, ..., 136, 136, 138]], dtype=uint8)

In [19]:
img_array.shape

(365, 449)

# Training data

In [27]:
training_data=[]

def create_training_data():
    for category in categories:
        path=os.path.join(datadir,category)
        class_num=categories.index(category)
        for img in os.listdir(path):
            try:
                img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
                img_array=cv2.resize(img_array,(50,50))
                training_data.append([img_array,class_num])
            except Exception as e:
                pass
            
create_training_data()

In [28]:
training_data

[[array([[ 57,  75,  42, ..., 103,  94,  52],
         [ 57,  72,  41, ...,  65,  45,  78],
         [ 47,  55,  52, ...,  53,  59,  68],
         ...,
         [118, 110, 105, ...,  53,  70,  76],
         [120, 121, 115, ...,  33,  81,  43],
         [123, 120, 117, ...,  78,  74,  77]], dtype=uint8), 0],
 [array([[ 99, 100, 107, ...,  21,  29,  28],
         [ 97, 113, 109, ...,  17,  26,  23],
         [ 94, 114, 109, ...,  10,  10,  24],
         ...,
         [ 93, 102,  96, ...,   7,   3,   4],
         [109,  87, 103, ...,   7,   4,   4],
         [101,  92, 102, ...,   8,   2,   4]], dtype=uint8), 0],
 [array([[245, 255, 252, ..., 255, 254, 255],
         [255,  62,  65, ...,  79,  68, 255],
         [255,  66,  67, ...,  79,  67, 255],
         ...,
         [255,  65,  59, ..., 218, 234, 255],
         [255, 220, 222, ..., 236, 244, 255],
         [255, 255, 255, ..., 255, 255, 255]], dtype=uint8), 0],
 [array([[ 59,  59,  58, ...,  50, 110,  54],
         [ 28,  29,  33, ..

In [30]:
import random
random.shuffle(training_data)

In [31]:
training_data

[[array([[ 57,  75,  42, ..., 103,  94,  52],
         [ 57,  72,  41, ...,  65,  45,  78],
         [ 47,  55,  52, ...,  53,  59,  68],
         ...,
         [118, 110, 105, ...,  53,  70,  76],
         [120, 121, 115, ...,  33,  81,  43],
         [123, 120, 117, ...,  78,  74,  77]], dtype=uint8), 0],
 [array([[245, 255, 252, ..., 255, 254, 255],
         [255,  62,  65, ...,  79,  68, 255],
         [255,  66,  67, ...,  79,  67, 255],
         ...,
         [255,  65,  59, ..., 218, 234, 255],
         [255, 220, 222, ..., 236, 244, 255],
         [255, 255, 255, ..., 255, 255, 255]], dtype=uint8), 0],
 [array([[115, 115, 110, ...,  37,  57,  31],
         [110, 113, 112, ...,  38,  46,  32],
         [110, 109, 111, ...,  40,  40,  30],
         ...,
         [101, 108, 107, ...,  69,  67,  58],
         [112, 113, 103, ...,  70,  77,  74],
         [ 92,  93, 101, ...,  81,  72,  75]], dtype=uint8), 1],
 [array([[ 59,  59,  58, ...,  50, 110,  54],
         [ 28,  29,  33, ..

In [32]:
X=[]
y=[]

In [33]:
for features,label in training_data:
    X.append(features)
    y.append(label)

In [34]:
X

[array([[ 57,  75,  42, ..., 103,  94,  52],
        [ 57,  72,  41, ...,  65,  45,  78],
        [ 47,  55,  52, ...,  53,  59,  68],
        ...,
        [118, 110, 105, ...,  53,  70,  76],
        [120, 121, 115, ...,  33,  81,  43],
        [123, 120, 117, ...,  78,  74,  77]], dtype=uint8),
 array([[245, 255, 252, ..., 255, 254, 255],
        [255,  62,  65, ...,  79,  68, 255],
        [255,  66,  67, ...,  79,  67, 255],
        ...,
        [255,  65,  59, ..., 218, 234, 255],
        [255, 220, 222, ..., 236, 244, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 array([[115, 115, 110, ...,  37,  57,  31],
        [110, 113, 112, ...,  38,  46,  32],
        [110, 109, 111, ...,  40,  40,  30],
        ...,
        [101, 108, 107, ...,  69,  67,  58],
        [112, 113, 103, ...,  70,  77,  74],
        [ 92,  93, 101, ...,  81,  72,  75]], dtype=uint8),
 array([[ 59,  59,  58, ...,  50, 110,  54],
        [ 28,  29,  33, ...,  50, 119,  55],
        [ 42,  4

In [35]:
y

[0, 0, 1, 0, 0, 1, 1, 1]

In [38]:
X=np.array(X)

In [39]:
X

array([[[ 57,  75,  42, ..., 103,  94,  52],
        [ 57,  72,  41, ...,  65,  45,  78],
        [ 47,  55,  52, ...,  53,  59,  68],
        ...,
        [118, 110, 105, ...,  53,  70,  76],
        [120, 121, 115, ...,  33,  81,  43],
        [123, 120, 117, ...,  78,  74,  77]],

       [[245, 255, 252, ..., 255, 254, 255],
        [255,  62,  65, ...,  79,  68, 255],
        [255,  66,  67, ...,  79,  67, 255],
        ...,
        [255,  65,  59, ..., 218, 234, 255],
        [255, 220, 222, ..., 236, 244, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[115, 115, 110, ...,  37,  57,  31],
        [110, 113, 112, ...,  38,  46,  32],
        [110, 109, 111, ...,  40,  40,  30],
        ...,
        [101, 108, 107, ...,  69,  67,  58],
        [112, 113, 103, ...,  70,  77,  74],
        [ 92,  93, 101, ...,  81,  72,  75]],

       ...,

       [[  1,   1,   1, ...,   5,   9,   9],
        [  1,   1,   1, ...,   6,   8,   5],
        [  1,   2,   5, ...,   3,   3,   6

In [40]:
X.shape

(8, 50, 50)

In [43]:
X=X.reshape(-1,50,50,1)

In [44]:
X.shape

(8, 50, 50, 1)

In [46]:
y=np.array(y).shape

(8,)